jobs:
  include:
    # - os: windows
    - os: osx
    - os: linux
      dist: bionic

notifications:
  email: false

language: java

# command to build
install:
  - ./gradlew assemble
  - ./gradlew build
  - ./gradlew jar
  - ./gradlew javadoc
  - ./gradlew fatJar

# command to run tests
script:
  - ./gradlew check

after_success: skip