notifications:
  email: false
language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# command to build
install:
  - "gradle assemble"

# command to run tests
script:
  - "gradle check"

after_success: